## <span style=color:green><center>ALGEBRA DE TENSORES (TALLER)</center></span>
### <span style=color:red><center>_David Alexis Arias Beltrán_</center></span>

#### Importar las librerias necesarias

In [2]:
import tensorflow as tf
import numpy as np

#### Tópicos esenciales

In [3]:
t0= tf.constant(278) #constante
print(t0)

tf.Tensor(278, shape=(), dtype=int32)


In [4]:
t1=tf.constant([4, 5, 3]) # vector. Se deben poner las comas necesariamente
print(t1)

tf.Tensor([4 5 3], shape=(3,), dtype=int32)


In [5]:
t23=tf.constant([[4,8,9],[1,1,0]]) #En la lista se encuentran 2 vectores con 3 elementos
print(t23) #Los dos deben tener la misma cantidad de elementos

tf.Tensor(
[[4 8 9]
 [1 1 0]], shape=(2, 3), dtype=int32)


In [6]:
tf456=tf.constant([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]],
                    [[16,17,18,67,26],[21,22,23,24,25],[26,27,28,29,30]],
                  [[52,7,9,9,1],[12,45,6,0,8],[9,1,12,45,98]]])
print(tf456) #3 listas c/u con 3 listas de 5 elementos

tf.Tensor(
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 67 26]
  [21 22 23 24 25]
  [26 27 28 29 30]]

 [[52  7  9  9  1]
  [12 45  6  0  8]
  [ 9  1 12 45 98]]], shape=(3, 3, 5), dtype=int32)


In [7]:
tf456.numpy()

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 67, 26],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]],

       [[52,  7,  9,  9,  1],
        [12, 45,  6,  0,  8],
        [ 9,  1, 12, 45, 98]]])

In [8]:
tf456.numpy().shape

(3, 3, 5)

#### Álgebra de vectores

In [9]:
a = tf.constant([[2,5,7],[8,5,3],[2,3,0]])
b = tf.constant([[5,5,1],[3,2,1],[1,8,9]])
print (a,"\n")
print (b,"\n")
print('Suma',"\n")
print(tf.add(a,b),"\n")#Para la suma deben tener la misma cantidad de elementos
print('Multiplicación',"\n")
print(tf.multiply(a,b),"\n")#Para la multiplicacion deben tener la misma cantidad de elementos
print(tf.matmul(a,b),"\n") #El número de listas=número de elementos de c/u

tf.Tensor(
[[2 5 7]
 [8 5 3]
 [2 3 0]], shape=(3, 3), dtype=int32) 

tf.Tensor(
[[5 5 1]
 [3 2 1]
 [1 8 9]], shape=(3, 3), dtype=int32) 

Suma 

tf.Tensor(
[[ 7 10  8]
 [11  7  4]
 [ 3 11  9]], shape=(3, 3), dtype=int32) 

Multiplicación 

tf.Tensor(
[[10 25  7]
 [24 10  3]
 [ 2 24  0]], shape=(3, 3), dtype=int32) 

tf.Tensor(
[[32 76 70]
 [58 74 40]
 [19 16  5]], shape=(3, 3), dtype=int32) 



In [10]:
print(a+b,"\n")
print(a*b, "\n")
print(a@b, "\n")

tf.Tensor(
[[ 7 10  8]
 [11  7  4]
 [ 3 11  9]], shape=(3, 3), dtype=int32) 

tf.Tensor(
[[10 25  7]
 [24 10  3]
 [ 2 24  0]], shape=(3, 3), dtype=int32) 

tf.Tensor(
[[32 76 70]
 [58 74 40]
 [19 16  5]], shape=(3, 3), dtype=int32) 



#### Funciones de Reducción

In [11]:
c = tf.constant([[3.35, 7.89],[23.1,1.1]])

print(c,"\n")
print("Valor máximo\n")
print(tf.reduce_max(c),"\n")
print("Valor mínimo\n")
print(tf.reduce_min(c),"\n")
print("Promedio\n")
print(tf.reduce_mean(c),"\n")
print("Valor máximo 2\n")
print(tf.argmax(c),"\n")#Valor mayor y ubicación del mismo
print("Softmax\n")
print(tf.nn.softmax(c),"\n")
print("Valor 3\n")
print(tf.reduce_sum(tf.nn.softmax(c),axis=1),"\n")

tf.Tensor(
[[ 3.35  7.89]
 [23.1   1.1 ]], shape=(2, 2), dtype=float32) 

Valor máximo

tf.Tensor(23.1, shape=(), dtype=float32) 

Valor mínimo

tf.Tensor(1.1, shape=(), dtype=float32) 

Promedio

tf.Tensor(8.86, shape=(), dtype=float32) 

Valor máximo 2

tf.Tensor([1 0], shape=(2,), dtype=int64) 

Softmax

tf.Tensor(
[[1.0560688e-02 9.8943931e-01]
 [1.0000000e+00 2.7894681e-10]], shape=(2, 2), dtype=float32) 

Valor 3

tf.Tensor([1. 1.], shape=(2,), dtype=float32) 



#### Tipos, formas y dimensión

In [12]:
t = tf.constant([
  [[0, 1.7, 8.2, 3, 3.4],
   [5, 61.12121, 7, 8, 9]],
  [[10, np.sqrt(12), 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 16*np.sqrt(4), 22, 2**2, 24],
   [25, 26, 27, 28, 29]],])
print(t.dtype,"\n")#tipos de datos que contienen
print(t.shape,"\n")#dimensiones
print(t.ndim,"\n")
print(t.shape[1],"\n")
print(tf.size(t.numpy()),"\n")#número de elementos

<dtype: 'float32'> 

(3, 2, 5) 

3 

2 

tf.Tensor(30, shape=(), dtype=int32) 



#### Indexación

In [13]:
t1 =  tf.constant([0, np.sqrt(81), 1, 2, 3, 5, 8**2, 54, 21, 34])
print("Primero: ", t1[0])
print("Segundo: ", t1[1])
print("Penúltimo: ", t1[-2].numpy())
print("Tercero de derecha a izquierda: ", t1[-3].numpy())

Primero:  tf.Tensor(0.0, shape=(), dtype=float32)
Segundo:  tf.Tensor(9.0, shape=(), dtype=float32)
Penúltimo:  21.0
Tercero de derecha a izquierda:  54.0


#### Extraer slices de un tensor

In [14]:
print('Todo', t1[:].numpy())
print('Antes la posición 7 ', t1[:7].numpy())
print('Desde la posición 1 hasta el final', t1[1:].numpy())
print('Desde la posición 5 hasta anterior a 7', t1[5:7].numpy())
print('Todos los elementos en posición par ', t1[::2].numpy())
print('Invertido todo el orden', t1[::-1].numpy())

Todo [ 0.  9.  1.  2.  3.  5. 64. 54. 21. 34.]
Antes la posición 7  [ 0.  9.  1.  2.  3.  5. 64.]
Desde la posición 1 hasta el final [ 9.  1.  2.  3.  5. 64. 54. 21. 34.]
Desde la posición 5 hasta anterior a 7 [ 5. 64.]
Todos los elementos en posición par  [ 0.  1.  3. 64. 21.]
Invertido todo el orden [34. 21. 54. 64.  5.  3.  2.  1.  9.  0.]


#### Indexación multi-eje

In [15]:
t23 = tf.constant([[1, 2, 3],[4, 5, 6],[7,8,9]])
print(t23.numpy())

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
print('Posición 0,1 = ',t23[0,1].numpy())#recordar que empieza desde 0
print('Segunda fila: ', t23[1,:].numpy())
print('Tercera columna: ', t23[:,2].numpy())
print('Última columna: ', t23[:,-1].numpy())
print('Primer elemento de la última columna: ', t23[0,-1].numpy())
print('Saltarse la primera columna: \n', t23[:,1:].numpy())
print('Saltarse la segunda fila y la primera columna: \n', t23[::2,1:].numpy())

Posición 0,1 =  2
Segunda fila:  [4 5 6]
Tercera columna:  [3 6 9]
Última columna:  [3 6 9]
Primer elemento de la última columna:  3
Saltarse la primera columna: 
 [[2 3]
 [5 6]
 [8 9]]
Saltarse la segunda fila y la primera columna: 
 [[2 3]
 [8 9]]


In [17]:
t = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],]) 
print(t.numpy())

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [18]:
print('Extrae la primera capa\n', t[0,:,:].numpy())
print('Extrae la segunda capa\n', t[1].numpy())
print('Extrae la primera capa, columna 1,2 y 3, fila 1\n', t[0,0,0:3].numpy())

Extrae la primera capa
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Extrae la segunda capa
 [[10 11 12 13 14]
 [15 16 17 18 19]]
Extrae la primera capa, columna 1,2 y 3, fila 1
 [0 1 2]


#### Manipular formas

In [19]:
x = tf.constant([[1],[2],[3]])
print(x.shape)
print(x.shape.as_list())

(3, 1)
[3, 1]


In [20]:
reshaped = tf.reshape(x,[1,3])
print(reshaped.numpy())
print(x.numpy())

[[1 2 3]]
[[1]
 [2]
 [3]]


#### Aplanar un tensor

In [28]:
print("t actual: \n", t.numpy())
flat = tf.reshape(t, [-1])
print("\n t aplanado: \n", flat.numpy())

t actual: 
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]

 t aplanado: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [30]:
print(tf.reshape(t, [2*3,5]))

tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32)


In [51]:
print(tf.reshape(t, [-1,3]))

tf.Tensor(
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]], shape=(10, 3), dtype=int32)


#### Tipos de conversiones cast

In [64]:
f32_tensor = tf.constant([87.1626, 14.2935, 6.3987], dtype = tf.float32)
print(f32_tensor)

f16_tensor = tf.cast(f32_tensor,dtype= tf.float16) # con float16 se aproximan decimales
print(f16_tensor)

u8_tensor = tf.cast(f16_tensor, dtype = tf.uint8) #enteros
print(u8_tensor)

tf.Tensor([87.1626 14.2935  6.3987], shape=(3,), dtype=float32)
tf.Tensor([87.2 14.3  6.4], shape=(3,), dtype=float16)
tf.Tensor([87 14  6], shape=(3,), dtype=uint8)


#### Radiodifusión

##### Estiramiento de vectores para lograr una adpatación hacia con otros para poder obtener la operación requerida

In [71]:
x = tf.constant([np.sqrt(9), 2**5 ,11])
x = tf.cast(x,dtype=tf.int32)
y = tf.constant(2)
z = tf.constant([2.5, 2.6 ,2.7])
z = tf.cast(z, dtype=tf.int32)
# el mismo resultado
print(tf.multiply(x,2))
print(x*y)
print(x*z)

tf.Tensor([ 6 64 22], shape=(3,), dtype=int32)
tf.Tensor([ 6 64 22], shape=(3,), dtype=int32)
tf.Tensor([ 6 64 22], shape=(3,), dtype=int32)


In [82]:
print(tf.broadcast_to([4,8,5,1], [5,4]).numpy())#el segundo parámetro debe consistir con # de elementos

[[4 8 5 1]
 [4 8 5 1]
 [4 8 5 1]
 [4 8 5 1]
 [4 8 5 1]]


#### Tensores de strings

In [83]:
st = tf.constant(["Este tensor es string",
                 "Cadena 2 de string",
                 "IA",
                 "Hola mundo"])
print(st)

tf.Tensor([b'Este tensor es string' b'Cadena 2 de string' b'IA' b'Hola mundo'], shape=(4,), dtype=string)


In [85]:
print(tf.strings.split(st))#Separa por cada parte del string(este  tensor...)

<tf.RaggedTensor [[b'Este', b'tensor', b'es', b'string'], [b'Cadena', b'2', b'de', b'string'], [b'IA'], [b'Hola', b'mundo']]>
